### ISSUE TITLE
Link error for get_time_since_boot

### ISSUE THREAD

**Issue by dwtowner** [mongoose-os-libs/dallas-rmt#2]
When building with a recent version of Mongoose OS dev environment the following linker error appears:

home/dant/Mongoose/ds18b20/build/objs/mosapp/libmosapp.a(DallasRmt.o): In function `DallasRmt::blockTillConversionComplete(unsigned char)':
/home/dant/Mongoose/ds18b20/deps/dallas-rmt/src/DallasRmt.cpp:35: undefined reference to `get_time_since_boot'

On inspection, the get_time_since_boot function in esp32/time.c is declared static, so would not be available to the Dallas RMT library. Maybe esp_timer_get_time() could be used instead?

**Comment by nliviu** [comment]
It has been fixed by https://github.com/mongoose-os-libs/dallas-rmt/commit/0d6a7799219675feb50cd296210c4369ceca95bb
Available with mos latest.
